### PR TITLE
add patch to extend libiconv with vs2019+win/arm64 support and revert submodules libxml2 and libxslt2

### PR DESCRIPTION
**Pull request by niyas-sait**
This patch extends the libiconv submodule with VS project files for VS 2019 and with support for win/arm64 target.

The patch also reverts submodule updates for the following modules

- libiconv ( Reason - Latest libiconv does not support MSVC 9.0 )
- libxml2 and libxslt ( Reason - python lxml compilation fails due to missing symbols)

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. Any recent libiconv version will probably do, but IIUC you reverted libxml2 to https://github.com/winlibs/libxml2/commit/cece36e81a2c38af4c9fdd32413feaf33e4735dc, right? That's too old. I'd like to stick with https://github.com/winlibs/libxml2/commit/6a6690cc9ed122b1e7a6385415e0859db93a0b43. What were the missing symbols? Do you have a build log for that?

**Comment by niyas-sait** [comment]
@scoder I looked into it a bit more and it seems like the problem is due to libxml2 header files by default trying to link against DLL by adding the import library prefixes which causes the many link error I saw previously.

```
etree.obj : error LNK2001: unresolved external symbol __imp_xmlC14NDocSave
etree.obj : error LNK2001: unresolved external symbol __imp_xmlSchematronValidateDoc
etree.obj : error LNK2001: unresolved external symbol __imp_xmlSchematronNewParserCtxt
etree.obj : error LNK2001: unresolved external symbol __imp_xmlSchematronNewDocParserCtxt

```

I think the fix would be to add a compile flag while building lxml extension modules to link against the static library. Something like following would work

```
--- a/setupinfo.py
+++ b/setupinfo.py
@@ -122,7 +122,7 @@ def ext_modules(static_include_dirs, static_library_dirs,
     _library_dirs = _prefer_reldirs(base_dir, library_dirs(static_library_dirs))
     _cflags = cflags(static_cflags)
     _ldflags = ['-isysroot', get_xcode_isysroot()] if sys.platform == 'darwin' else None
-    _define_macros = define_macros()
+    _define_macros = [('LIBXML_STATIC', 1)]
     _libraries = libraries()

     if _library_dirs:
```

I have reverted the submodule update for libxml2 and libxslt to use the latest as before. So this can be merged if you are okay.

And I can open a PR for lxml to add this extra change build against the static library

**Comment by niyas-sait** [comment]
@scoder Just pinging in case you missed previous update

**Comment by scoder** [comment]
Not sure why you want a macro for this. Isn't it just something to add to the `extra_objects` of the `Extension` setup further down? That's what the `static_binaries` argument is there for.

**Comment by niyas-sait** [comment]
> Not sure why you want a macro for this. Isn't it just something to add to the `extra_objects` of the `Extension` setup further down? That's what the `static_binaries` argument is there for.

There may be a better way to add this flag. I am not sure. But for compiling against static library we will need to define LIBXML_STATIC during the c/c++ compilation. 

If you are happy we could merge this patch and could look into options of defining the macro while building lxml ?

**Comment by scoder** [comment]
I pushed https://github.com/lxml/lxml/commit/7837d13c450eaf48dd9b05c60e3c245b3c7ffe9b. Does that solve the issue?

**Comment by niyas-sait** [comment]
> I pushed [lxml/lxml@7837d13](https://github.com/lxml/lxml/commit/7837d13c450eaf48dd9b05c60e3c245b3c7ffe9b). Does that solve the issue?

Yes I think that should work. Thanks

**Comment by scoder** [comment]
Thanks a lot. Let's see what appveyor makes of this.

**Comment by niyas-sait** [comment]
Thanks, @scoder. Could you make a release with the appveyor artifacts please?

**Comment by niyas-sait** [comment]
Thanks @scoder. I've tried with top of lxml and everything seems to be working fine

**Pull request merged**
