### PR TITLE
github actions workflow

### PR DESCRIPTION
**Pull request by mugiseyebrows**
In case you need one

### CODE REVIEW

**Comment by EwoutH** [comment]
This is awesome, thanks a lot!

@scoder I took a look at [the workflow](https://github.com/mugiseyebrows/libxml2-win-binaries/actions/runs/3666008860), and it's looks good, at least for a first iteration. Can we merge this?

**Comment by scoder** [comment]
Thanks!

**Comment by scoder** [comment]
Excellent. Works really nicely. Thanks a lot!

**Comment by mugiseyebrows** [comment]
Cool! Thank you.

**Pull request merged**
